apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: porttrack-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: porttrack-monitoring
data:
  alertmanager.yml: |
    global:
      slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
      smtp_smarthost: 'localhost:25'
      smtp_from: 'alertmanager@porttrack.com'
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: critical
          receiver: 'pagerduty-critical'
          continue: true
        - match:
            severity: warning
          receiver: 'slack-notifications'
    
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#porttrack-alerts'
            title: '🚨 PortTrack Alert'
            text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ .Annotations.description }}{{ end }}'
            actions:
              - type: button
                text: 'View in Grafana'
                url: '{{ .CommonAnnotations.grafana_url }}'
            send_resolved: true
            icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
            username: 'PortTrack AlertManager'
      
      - name: 'pagerduty-critical'
        pagerduty_configs:
          - routing_key: 'YOUR_PAGERDUTY_KEY'
            description: '{{ .CommonAnnotations.summary }}'
            severity: '{{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}'
            client: 'PortTrack AlertManager'
            client_url: '{{ .CommonAnnotations.grafana_url }}'
      
      - name: 'email-notifications'
        email_configs:
          - to: 'devops@porttrack.com'
            send_resolved: true
            headers:
              subject: 'PortTrack Alert: {{ .CommonAnnotations.summary }}'
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']
      
      - source_match:
          alertname: 'NodeDown'
        target_match:
          alertname: 'HighCPUUsage'
        equal: ['instance']
      
      - source_match:
          alertname: 'NodeDown'
        target_match:
          alertname: 'HighMemoryUsage'
        equal: ['instance']
