apiVersion: apps/v1
kind: Deployment
metadata:
  name: porttrack-app
  namespace: porttrack-production
  labels:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: porttrack-app
      environment: production
  template:
    metadata:
      labels:
        app.kubernetes.io/name: porttrack-app
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: porttrack-app
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: porttrack-app
        image: ghcr.io/porttrack/platform:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_NAME
          value: "PortTrack"
        - name: APP_VERSION
          value: "latest"
        - name: DB_HOST
          value: "porttrack-postgresql-production"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "porttrack_production"
        - name: REDIS_HOST
          value: "porttrack-redis-production"
        - name: REDIS_PORT
          value: "6379"
        - name: ELASTICSEARCH_HOST
          value: "porttrack-elasticsearch-production"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: METRICS_PORT
          value: "9090"
        - name: LOG_LEVEL
          value: "warn"
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: porttrack-secrets-production
              key: auth0-domain
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: porttrack-secrets-production
              key: auth0-client-id
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: porttrack-secrets-production
              key: auth0-client-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: config-volume
        configMap:
          name: porttrack-config-production
      - name: logs-volume
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - porttrack-app
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-type: application
---
apiVersion: v1
kind: Service
metadata:
  name: porttrack-app-service
  namespace: porttrack-production
  labels:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
    environment: production
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: porttrack-app
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: porttrack-config-production
  namespace: porttrack-production
  labels:
    app.kubernetes.io/name: porttrack-config
    app.kubernetes.io/part-of: porttrack-platform
    environment: production
data:
  APP_NAME: "PortTrack"
  APP_VERSION: "latest"
  APP_ENV: "production"
  DB_HOST: "porttrack-postgresql-production"
  DB_PORT: "5432"
  DB_NAME: "porttrack_production"
  REDIS_HOST: "porttrack-redis-production"
  REDIS_PORT: "6379"
  ELASTICSEARCH_HOST: "porttrack-elasticsearch-production"
  ELASTICSEARCH_PORT: "9200"
  LOG_LEVEL: "warn"
  METRICS_PORT: "9090"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  ALERT_CPU_THRESHOLD: "80"
  ALERT_MEMORY_THRESHOLD: "80"
  ALERT_DISK_THRESHOLD: "90"
  ALERT_RESPONSE_TIME_THRESHOLD: "2000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: porttrack-app-hpa
  namespace: porttrack-production
  labels:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: porttrack-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
