apiVersion: apps/v1
kind: Deployment
metadata:
  name: porttrack-app
  namespace: porttrack
  labels:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: porttrack-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: porttrack-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: porttrack-app
        image: ghcr.io/porttrack/platform:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_NAME
          value: "PortTrack"
        - name: APP_VERSION
          value: "1.0.0"
        - name: DB_HOST
          value: "porttrack-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "porttrack"
        - name: REDIS_HOST
          value: "porttrack-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: METRICS_PORT
          value: "9090"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
