apiVersion: v1
kind: Service
metadata:
  name: porttrack-app-service
  namespace: porttrack
  labels:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: porttrack-app
    app.kubernetes.io/part-of: porttrack-platform
---
apiVersion: v1
kind: Service
metadata:
  name: porttrack-postgresql
  namespace: porttrack
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: porttrack-platform
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: porttrack-platform
---
apiVersion: v1
kind: Service
metadata:
  name: porttrack-redis
  namespace: porttrack
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: porttrack-platform
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: porttrack-platform
---
apiVersion: v1
kind: Service
metadata:
  name: porttrack-elasticsearch
  namespace: porttrack
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: porttrack-platform
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: porttrack-platform
